chain-id: 2248 
network-id: 2248
execution-endpoint: http://127.0.0.1:8551
rpc-host: 0.0.0.0
rpc-port: 4000
http-host: 0.0.0.0
http-cors-domain: "*"
http-port: 3500
p2p-tcp-port: 13000
p2p-udp-port: 12000
p2p-quic-port: 13000
min-sync-peers: 0
p2p-max-peers: 50
verbosity: debug
slots-per-archive-point: 32
no-discovery: true
disable-monitoring: false
monitoring-host: 0.0.0.0
monitoring-port: 8080
accept-terms-of-use: true
no-discovery: true 
pprof: true
pprofaddr: 0.0.0.0
pprofport: 6060
p2p-static-id: true
contract-deployment-block: 0
